# Generated by Django 5.1.3 on 2024-12-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented_posts",
                to="network.comment",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_posts",
                to="network.like",
            ),
        ),
    ]
