# Generated by Django 5.1.3 on 2024-12-21 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0002_post_comments_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
