# Generated by Django 5.1.3 on 2024-12-21 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_remove_post_comments_remove_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date_posted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
