# Generated by Django 5.1.3 on 2024-12-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_follow_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="status",
            field=models.BooleanField(default=""),
        ),
    ]
