# Generated by Django 5.1.3 on 2024-12-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0006_alter_like_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="follow",
            field=models.BooleanField(),
        ),
    ]
