# Generated by Django 5.1.3 on 2024-12-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_alter_follow_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count",
            field=models.IntegerField(default=0),
        ),
    ]
