# Generated by Django 5.1.3 on 2025-01-02 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="students",
            field=models.ManyToManyField(
                default=None, related_name="schedule", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
