# Generated by Django 5.1.3 on 2025-01-11 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_event_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "attachment_1",
                    models.FileField(blank=True, null=True, upload_to="web/files/"),
                ),
                (
                    "attachment_2",
                    models.FileField(blank=True, null=True, upload_to="web/files/"),
                ),
                ("status", models.CharField(max_length=100)),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="card", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
