# Generated by Django 5.1.3 on 2025-01-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_progresscard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progresscard",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("To Do", "todo"),
                    ("On Going", "ongoing"),
                    ("Completed", "completed"),
                ],
                max_length=20,
            ),
        ),
    ]
