# Generated by Django 5.1.3 on 2024-12-05 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_remove_listings_user_listings_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listings",
            name="image",
        ),
    ]
