# Generated by Django 5.1.3 on 2024-12-06 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_alter_listings_image_bid_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bid_object",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to="auctions.listings",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_object",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commented",
                to="auctions.listings",
            ),
        ),
    ]
