# Generated by Django 5.1.3 on 2024-12-09 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0012_rename_starting_bid_listings_current_bid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchlist",
            name="item",
        ),
        migrations.AddField(
            model_name="watchlist",
            name="item",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="auctions.listings",
            ),
        ),
    ]
