# Generated by Django 5.1.3 on 2024-12-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0013_remove_watchlist_item_watchlist_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="item",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list",
                to="auctions.listings",
            ),
        ),
    ]
